### ISSUE TITLE
Bug : Fix the deposit type URI in the dedup-sites API for nickel.

### ISSUE THREAD

**Issue by punith300i** [DARPA-CRITICALMAAS/ta2-minmod-kg#44]
<img width="914" alt="Screenshot 2024-12-09 at 1 44 08 AM" src="https://github.com/user-attachments/assets/1bafc495-f62c-4a84-8a14-1ce6e76045c1">

**Comment by binh-vu** [comment]
Reason: data from Inferlink is wrong (contain empty `normalized_uri` for `deposit_type_candidate`) - the validator did not run on those files.
